### ISSUE TITLE
Nextcloud 21

### ISSUE THREAD

**Issue by sunjam** [e-alfred/flowupload#305]
Please update for latest [Nextcloud 21 release](https://nextcloud.com/blog/nextcloud-hub-21-out-with-up-to-10x-better-performance-whiteboard-and-more-collaboration-features/).

**Comment by JonathanTreffler** [comment]
Can you confirm the current version runs smoothly on nextcloud 21 ?

**Comment by sunjam** [comment]
I am not updating as too many apps are labelled unsupported. Hopefully
others can test. Apologies, I simply do not have time to break my instance.
Flowupload rocks btw.

**Comment by chandlben** [comment]
I have upgraded and can confirm that, at least for me, it does not work with Nextcloud 21.

**Comment by JonathanTreffler** [comment]
> I have upgraded and can confirm that, at least for me, it does not work with Nextcloud 21.

Thanks for testing :)

**Comment by JonathanTreffler** [comment]
If i have time in the next days, i will try to find out what causes the compatibility issues on Nextcloud 21.

**Comment by e-alfred** [comment]
@chandlben What kind of errors do you get? I tried it on Nextcloud 21 on a test instance and it works so far.

**Comment by chandlben** [comment]
Flow upload simply says "Error" to each uploading file but in the system logs this is generated:
```
Exception: Call to a member function file_exists() on null
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 993:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 37:

OC::handleRequest()

Caused by Error: Call to a member function file_exists() on null
/var/www/nextcloud/apps/flowupload/lib/Controller/UploadController.php - line 84:

OC\Files\Filesystem::file_exists()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:

OCA\flowupload\Controller\UploadController->upload()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 993:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 37:

OC::handleRequest()
```
I removed and then added the app again to no avail.

**Comment by Kevin-Lyle-Ruiz** [comment]
Receiving the same error as well.

**Comment by e-alfred** [comment]
I added a potential fix (https://github.com/e-alfred/flowupload/commit/bb6c554679aa890deff285ddd27ec32f85b02a02), can you test it by manually adding the lines changes and see if it works?

@JonathanTreffler I tried to build it again, but it seems like there is a problem with the Vue frontend code:

```
Uncaught TypeError: Object(...) is not a function
    <anonymous> App.vue:3
    Webpack 3
App.vue:3:111
    <anonymous> App.vue:3
    Webpack 3

```

**Comment by JonathanTreffler** [comment]
> I added a potential fix (https://github.com/e-alfred/flowupload/commit/bb6c554679aa890deff285ddd27ec32f85b02a02), can you test it by manually adding the changed lines and see if it works? The filesystem calls need to be set up separately now it seems.
> 
> @JonathanTreffler I tried to build it again, but it seems like there is a problem with the Vue frontend code:
> 
> ```
> Uncaught TypeError: Object(...) is not a function
>     <anonymous> App.vue:3
>     Webpack 3
> App.vue:3:111
>     <anonymous> App.vue:3
>     Webpack 3
> 
> ```

The frontend problem is likely because of a dependency update. I am currently sick, but i will look into that in a few days.

**Comment by MarcSchoendorf** [comment]
Any news about the update? App is incompatible with NC 21 for me too.

**Comment by stratege1401** [comment]
Sorry to add my complain, it failed with me too:

`

Exception: Call to a member function file_exists() on null/config/www/nextcloud/lib/private/AppFramework/App.php - line 157:OC\AppFramework\Http\Dispatcher->dispatch()/config/www/nextcloud/lib/private/Route/Router.php - line 302:OC\AppFramework\App::main()/config/www/nextcloud/lib/base.php - line 993:OC\Route\Router->match()/config/www/nextcloud/index.php - line 37:OC::handleRequest()Causé parError: Call to a member function file_exists() on null/config/www/nextcloud/apps/flowupload/lib/Controller/UploadController.php - line 84:OC\Files\Filesystem::file_exists()/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:OCA\flowupload\Controller\UploadController->upload()/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:OC\AppFramework\Http\Dispatcher->executeController()/config/www/nextcloud/lib/private/AppFramework/App.php - line 157:OC\AppFramework\Http\Dispatcher->dispatch()/config/www/nextcloud/lib/private/Route/Router.php - line 302:OC\AppFramework\App::main()/config/www/nextcloud/lib/base.php - line 993:OC\Route\Router->match()/config/www/nextcloud/index.php - line 37:OC::handleRequest()
--


`

**Comment by luffy51k** [comment]
the same problem.

**Comment by geokh** [comment]
any new update for the issue ?

**Comment by pm-pm** [comment]
One Question: NC21 do support PHP7. Why can we not use the Application with PHP7 support with NC21?
Or am i wrong?

**Comment by patricksebastien** [comment]
It is the only app not updated on my instance, stopping me to finally save my precious cpu (nextcloud 21 reduce load by 80% <-> 90%).

**Comment by LostInCompilation** [comment]
Well, I think the app is dead...

**Comment by sunjam** [comment]
The last commit was 4 days ago.  Be patient.

**Comment by JonathanTreffler** [comment]
> Well, I think the app is dead...

Nope, I just looked into the issue and the fix for Nextcloud 22 is literally adding a "/" to an input.
The current version in master works for me in Nextcloud 22 without any problems.

**Comment by JonathanTreffler** [comment]
> The frontend problem is likely because of a dependency update. I am currently sick, but I will look into that in a few days.

Sorry for taking so long, but the frontend build is now fixed. It was a dependency update of Vue-loader, which does not support Vue version 2 anymore. At some point we will have to upgrade to vue 3, but the Nextcloud eco system sadly is not ready for vue 3 yet.

**Comment by JonathanTreffler** [comment]
For all of you, that have had to wait far too long:
Heres a "beta" release for Nextcloud 22:
[flowupload.zip](https://github.com/e-alfred/flowupload/files/6796846/flowupload.zip)

In my testing everything works, but if you have any problems with it, just comment here.

**Comment by JonathanTreffler** [comment]
@e-alfred I think we can publish a new release soon.

**Comment by e-alfred** [comment]
@JonathanTreffler Thanks for your work, I will publish a new version soon if no other problems come up.

**Comment by elasticSteel** [comment]
> For all of you, that have had to wait far too long:
> Heres a "beta" release for Nextcloud 22:

will this also work on 21?

**Comment by sunjam** [comment]
Try installing it on 21 and let us know.

**Comment by elasticSteel** [comment]
> Try installing it on 21 and let us know.

I am sorry, I can't test it myself at the moment. I do not have a test system available at the moment :(
But if I manage to find out, I'll let you know.

**Comment by elasticSteel** [comment]
> > Try installing it on 21 and let us know.
> 
> I am sorry, I can't test it myself at the moment. I do not have a test system available at the moment :(
> But if I manage to find out, I'll let you know.

Did a quick test on a fresh 21 install. It seems to work just fine :-)

**Comment by nsturtz** [comment]
> Flow upload simply says "Error" to each uploading file but in the system logs this is generated:
> 
> ```
> Exception: Call to a member function file_exists() on null
> /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
> 
> OC\AppFramework\Http\Dispatcher->dispatch()
> 
> /var/www/nextcloud/lib/private/Route/Router.php - line 302:
> 
> OC\AppFramework\App::main()
> 
> /var/www/nextcloud/lib/base.php - line 993:
> 
> OC\Route\Router->match()
> 
> /var/www/nextcloud/index.php - line 37:
> 
> OC::handleRequest()
> 
> Caused by Error: Call to a member function file_exists() on null
> /var/www/nextcloud/apps/flowupload/lib/Controller/UploadController.php - line 84:
> 
> OC\Files\Filesystem::file_exists()
> 
> /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:
> 
> OCA\flowupload\Controller\UploadController->upload()
> 
> /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:
> 
> OC\AppFramework\Http\Dispatcher->executeController()
> 
> /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
> 
> OC\AppFramework\Http\Dispatcher->dispatch()
> 
> /var/www/nextcloud/lib/private/Route/Router.php - line 302:
> 
> OC\AppFramework\App::main()
> 
> /var/www/nextcloud/lib/base.php - line 993:
> 
> OC\Route\Router->match()
> 
> /var/www/nextcloud/index.php - line 37:
> 
> OC::handleRequest()
> ```
> 
> I removed and then added the app again to no avail.

Still is happening in NC 21

**Comment by LostInCompilation** [comment]
Will there be an official release for NC21 too? Or just NC22?

**Comment by JonathanTreffler** [comment]
> Will there be an official release for NC21 too? Or just NC22?

I hope and plan so, but I need to be able to reproduce the error :/

**Comment by nikkuexe** [comment]
I've testing on NC 21.0.3 with PHP 7.4.3 and it works fine.

**Comment by hilmiger** [comment]
for nextcloud 21 it works

**Comment by hilmiger** [comment]
> For all of you, that have had to wait far too long:
> Heres a "beta" release for Nextcloud 22:
> [flowupload.zip](https://github.com/e-alfred/flowupload/files/6796846/flowupload.zip)
> 
> In my testing everything works, but if you have any problems with it, just comment here.

for nextcloud 21 it works :)

**Comment by e-alfred** [comment]
@JonathanTreffler I am currently building a new release, but I am getting a lot of errors at the 'npm run build' step:

```
WARNING in 
/flowupload/src/App.vue
   16:6   warning  Attribute "v-if" should go before ":id"                                     vue/attributes-order
  251:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  255:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  256:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  258:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  259:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  277:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  281:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  282:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  284:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  285:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  291:24  warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  293:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  294:7   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  297:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  298:7   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  308:13  warning  The property or function OC.generateUrl was deprecated in Nextcloud 19.0.0  @nextcloud/no-deprecations
  396:4   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  406:11  warning  The property or function OCA.Search was deprecated in Nextcloud 20.0.0      @nextcloud/no-deprecations
  432:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  508:4   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
  523:4   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations

✖ 99 problems (77 errors, 22 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.


ERROR in 
/temp/flowupload/src/App.vue
   16:6   error  This 'v-if' should be moved to the wrapper element                                                                                                                             vue/no-use-v-if-with-v-for
  137:8   error  Elements in iteration expect to have 'v-bind:key' directives                                                                                                                   vue/require-v-for-key
  137:51  error  The 'filteredFiles' variable inside 'v-for' directive should be replaced with a computed property that returns filtered array instead. You should not mix 'v-for' with 'v-if'  vue/no-use-v-if-with-v-for
  222:3   error  The "AppNavigationSettings" component has been registered but not used                                                                                                         vue/no-unused-components
  223:3   error  The "AppSidebar" component has been registered but not used                                                                                                                    vue/no-unused-components
  224:3   error  The "AppSidebarTab" component has been registered but not used                                                                                                                 vue/no-unused-components
  227:3   error  The "ActionLink" component has been registered but not used                                                                                                                    vue/no-unused-components
  228:3   error  The "AppNavigationIconBullet" component has been registered but not used                                                                                                       vue/no-unused-components
  229:3   error  The "ActionCheckbox" component has been registered but not used                                                                                                                vue/no-unused-components
  230:3   error  The "ActionInput" component has been registered but not used                                                                                                                   vue/no-unused-components
  231:3   error  The "ActionRouter" component has been registered but not used                                                                                                                  vue/no-unused-components
  232:3   error  The "ActionText" component has been registered but not used                                                                                                                    vue/no-unused-components
  233:3   error  The "ActionTextEditable" component has been registered but not used                                                                                                            vue/no-unused-components
  251:5   error  '$' is not defined                                                                                                                                                             no-undef
  255:5   error  '$' is not defined                                                                                                                                                             no-undef
  256:6   error  '$' is not defined                                                                                                                                                             no-undef
  258:5   error  '$' is not defined                                                                                                                                                             no-undef
  259:6   error  '$' is not defined                                                                                                                                                             no-undef
  277:5   error  '$' is not defined                                                                                                                                                             no-undef
  281:5   error  '$' is not defined                                                                                                                                                             no-undef
  282:6   error  '$' is not defined                                                                                                                                                             no-undef
  284:5   error  '$' is not defined                                                                                                                                                             no-undef
  285:6   error  '$' is not defined                                                                                                                                                             no-undef
  291:24  error  '$' is not defined                                                                                                                                                             no-undef
  292:20  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  293:6   error  '$' is not defined                                                                                                                                                             no-undef
  294:7   error  '$' is not defined                                                                                                                                                             no-undef
  296:27  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  297:6   error  '$' is not defined                                                                                                                                                             no-undef
  298:7   error  '$' is not defined                                                                                                                                                             no-undef
  331:19  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  332:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
  333:7   error  Unexpected console statement                                                                                                                                                   no-console
  337:7   error  Opening curly brace does not appear on the same line as controlling statement                                                                                                  brace-style
  341:26  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  342:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
  345:26  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  346:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
  349:26  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  350:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
  359:21  error  Expected '!==' and instead saw '!='                                                                                                                                            eqeqeq
  381:4   error  Unexpected console statement                                                                                                                                                   no-console
  396:4   error  '$' is not defined                                                                                                                                                             no-undef
  406:7   error  Do not use 'new' for side effects                                                                                                                                              no-new
  413:28  error  Expected '!==' and instead saw '!='                                                                                                                                            eqeqeq
  422:4   error  Unexpected console statement                                                                                                                                                   no-console
  432:5   error  '$' is not defined                                                                                                                                                             no-undef
  466:32  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  474:30  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  482:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  483:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  484:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  485:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  486:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  487:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  488:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  489:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  490:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  491:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  492:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  493:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  495:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  496:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  497:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  498:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  499:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  500:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  508:4   error  '$' is not defined                                                                                                                                                             no-undef
  523:4   error  '$' is not defined                                                                                                                                                             no-undef
  551:33  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  556:23  error  Expected '!==' and instead saw '!='                                                                                                                                            eqeqeq
  563:42  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  570:42  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  577:46  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  598:18  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
  605:4   error  Unexpected console statement                                                                                                                                                   no-console
  606:4   error  Unexpected console statement                                                                                                                                                   no-console

✖ 99 problems (77 errors, 22 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flowupload@0.1.8 build: `NODE_ENV=production webpack --progress --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flowupload@0.1.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

**Comment by JonathanTreffler** [comment]
> @JonathanTreffler I am currently building a new release, but I am getting a lot of errors at the 'npm run build' step:
> 
> ```
> WARNING in 
> /flowupload/src/App.vue
>    16:6   warning  Attribute "v-if" should go before ":id"                                     vue/attributes-order
>   251:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   255:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   256:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   258:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   259:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   277:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   281:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   282:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   284:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   285:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   291:24  warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   293:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   294:7   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   297:6   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   298:7   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   308:13  warning  The property or function OC.generateUrl was deprecated in Nextcloud 19.0.0  @nextcloud/no-deprecations
>   396:4   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   406:11  warning  The property or function OCA.Search was deprecated in Nextcloud 20.0.0      @nextcloud/no-deprecations
>   432:5   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   508:4   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
>   523:4   warning  The global property or function $ was deprecated in Nextcloud 19.0.0        @nextcloud/no-deprecations
> 
> ✖ 99 problems (77 errors, 22 warnings)
>   0 errors and 1 warning potentially fixable with the `--fix` option.
> 
> 
> ERROR in 
> /temp/flowupload/src/App.vue
>    16:6   error  This 'v-if' should be moved to the wrapper element                                                                                                                             vue/no-use-v-if-with-v-for
>   137:8   error  Elements in iteration expect to have 'v-bind:key' directives                                                                                                                   vue/require-v-for-key
>   137:51  error  The 'filteredFiles' variable inside 'v-for' directive should be replaced with a computed property that returns filtered array instead. You should not mix 'v-for' with 'v-if'  vue/no-use-v-if-with-v-for
>   222:3   error  The "AppNavigationSettings" component has been registered but not used                                                                                                         vue/no-unused-components
>   223:3   error  The "AppSidebar" component has been registered but not used                                                                                                                    vue/no-unused-components
>   224:3   error  The "AppSidebarTab" component has been registered but not used                                                                                                                 vue/no-unused-components
>   227:3   error  The "ActionLink" component has been registered but not used                                                                                                                    vue/no-unused-components
>   228:3   error  The "AppNavigationIconBullet" component has been registered but not used                                                                                                       vue/no-unused-components
>   229:3   error  The "ActionCheckbox" component has been registered but not used                                                                                                                vue/no-unused-components
>   230:3   error  The "ActionInput" component has been registered but not used                                                                                                                   vue/no-unused-components
>   231:3   error  The "ActionRouter" component has been registered but not used                                                                                                                  vue/no-unused-components
>   232:3   error  The "ActionText" component has been registered but not used                                                                                                                    vue/no-unused-components
>   233:3   error  The "ActionTextEditable" component has been registered but not used                                                                                                            vue/no-unused-components
>   251:5   error  '$' is not defined                                                                                                                                                             no-undef
>   255:5   error  '$' is not defined                                                                                                                                                             no-undef
>   256:6   error  '$' is not defined                                                                                                                                                             no-undef
>   258:5   error  '$' is not defined                                                                                                                                                             no-undef
>   259:6   error  '$' is not defined                                                                                                                                                             no-undef
>   277:5   error  '$' is not defined                                                                                                                                                             no-undef
>   281:5   error  '$' is not defined                                                                                                                                                             no-undef
>   282:6   error  '$' is not defined                                                                                                                                                             no-undef
>   284:5   error  '$' is not defined                                                                                                                                                             no-undef
>   285:6   error  '$' is not defined                                                                                                                                                             no-undef
>   291:24  error  '$' is not defined                                                                                                                                                             no-undef
>   292:20  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   293:6   error  '$' is not defined                                                                                                                                                             no-undef
>   294:7   error  '$' is not defined                                                                                                                                                             no-undef
>   296:27  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   297:6   error  '$' is not defined                                                                                                                                                             no-undef
>   298:7   error  '$' is not defined                                                                                                                                                             no-undef
>   331:19  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   332:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
>   333:7   error  Unexpected console statement                                                                                                                                                   no-console
>   337:7   error  Opening curly brace does not appear on the same line as controlling statement                                                                                                  brace-style
>   341:26  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   342:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
>   345:26  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   346:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
>   349:26  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   350:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
>   359:21  error  Expected '!==' and instead saw '!='                                                                                                                                            eqeqeq
>   381:4   error  Unexpected console statement                                                                                                                                                   no-console
>   396:4   error  '$' is not defined                                                                                                                                                             no-undef
>   406:7   error  Do not use 'new' for side effects                                                                                                                                              no-new
>   413:28  error  Expected '!==' and instead saw '!='                                                                                                                                            eqeqeq
>   422:4   error  Unexpected console statement                                                                                                                                                   no-console
>   432:5   error  '$' is not defined                                                                                                                                                             no-undef
>   466:32  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   474:30  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   482:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   483:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   484:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   485:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   486:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   487:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   488:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   489:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   490:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   491:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   492:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   493:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   495:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   496:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   497:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   498:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   499:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   500:4   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
>   508:4   error  '$' is not defined                                                                                                                                                             no-undef
>   523:4   error  '$' is not defined                                                                                                                                                             no-undef
>   551:33  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   556:23  error  Expected '!==' and instead saw '!='                                                                                                                                            eqeqeq
>   563:42  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   570:42  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   577:46  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   598:18  error  Expected '===' and instead saw '=='                                                                                                                                            eqeqeq
>   605:4   error  Unexpected console statement                                                                                                                                                   no-console
>   606:4   error  Unexpected console statement                                                                                                                                                   no-console
> 
> ✖ 99 problems (77 errors, 22 warnings)
>   0 errors and 1 warning potentially fixable with the `--fix` option.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! flowupload@0.1.8 build: `NODE_ENV=production webpack --progress --config webpack.prod.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the flowupload@0.1.8 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> 
> ```

I will look into it. Does the result of the compile work ?

**Comment by JonathanTreffler** [comment]
> I will look into it. Does the result of the compile work ?

Sorry for taking so long. I fixed all build problems in #427 today and we can release a new version now :)

@e-alfred Will you have time to create the release soon ?

**Comment by LostInCompilation** [comment]
Yaay, thanks :)

**Comment by e-alfred** [comment]
@JonathanTreffler The build works now, but I still get an error when loading the app:

`Uncaught SyntaxError: unexpected token: ':'flowupload-main.js:185:16`

**Comment by JonathanTreffler** [comment]
> @JonathanTreffler The build works now, but I still get an error when loading the app:
> 
> `Uncaught SyntaxError: unexpected token: ':'flowupload-main.js:185:16`

Weird. I will try to replicate the issue.

**Comment by vandman** [comment]
Hi, 
On nc 21.0.4, I always have NS_BINDING_ABORTED on main.js in firefox debug mode/network.
I have a white page under the nc top "menu", nothing happens???
Regards,
Vandman

**Comment by christoschronopoulos** [comment]
On NC21 I installed the 1.1.3 version of flowupload but I got a blank page below the dashboard. Then I tried the zip from this thread. 

> For all of you, that have had to wait far too long: Heres a "beta" release for Nextcloud 22: [flowupload.zip](https://github.com/e-alfred/flowupload/files/6796846/flowupload.zip)
> 
> In my testing everything works, but if you have any problems with it, just comment here.

It worked a few times but now it says "Completed" when the upload is done and yet I cannot find the files. I tried uploading to several folders but they remain empty even after a "completed" upload.

**Comment by stratege1401** [comment]
NC 22.2.5 canal stable, 
Debian 11.2, 
PHP 8.0.16;
Apache 2.4.52,
Fileupload beta fron #305

Does not work.
log:

```
{"reqId":"rz0fCY9L3ueNMy9VFfPL","level":1,-time-19+00:00",XXX,"user":"XXX","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"rz0fCY9L3ueNMy9VFfPL","level":1,-time-19+00:00",XXX,"user":"XXX","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"rz0fCY9L3ueNMy9VFfPL","level":1,-time-19+00:00",XXX,"user":"XXX","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"rz0fCY9L3ueNMy9VFfPL","level":1,-time-19+00:00",XXX,"user":"XXX","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"rz0fCY9L3ueNMy9VFfPL","level":1,-time-19+00:00",XXX,"user":"XXX","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"rz0fCY9L3ueNMy9VFfPL","level":1,-time-19+00:00",XXX,"user":"XXX","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"rz0fCY9L3ueNMy9VFfPL","level":1,-time-19+00:00",XXX,"user":"XXX","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"dTFpZTvECfRogbIi9KZF","level":3,-time-34+00:00",XXX,"user":"XXX","app":"index","method":"POST","url":"/index.php/apps/flowupload/upload","message":"Call to a member function file_exists() on null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1","exception":{"Exception":"Exception","Message":"Call to a member function file_exists() on null","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Call to a member function file_exists() on null","Code":0,"Trace":[{"file":"/var/www/html/apps/flowupload/lib/Controller/UploadController.php","line":84,"function":"file_exists","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"upload","class":"OCA\\flowupload\\Controller\\UploadController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/Files/Filesystem.php","Line":678},"CustomMessage":"--"}}
{"reqId":"wRz7c8Ng2Q1HqR5LYeyL","level":3,-time-34+00:00",XXX,"user":"XXX","app":"index","method":"POST","url":"/index.php/apps/flowupload/upload","message":"Call to a member function file_exists() on null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1","exception":{"Exception":"Exception","Message":"Call to a member function file_exists() on null","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Call to a member function file_exists() on null","Code":0,"Trace":[{"file":"/var/www/html/apps/flowupload/lib/Controller/UploadController.php","line":84,"function":"file_exists","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"upload","class":"OCA\\flowupload\\Controller\\UploadController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/Files/Filesystem.php","Line":678},"CustomMessage":"--"}}
{"reqId":"ZjKfmjCMZpocoPHf8o9z","level":3,-time-34+00:00",XXX,"user":"XXX","app":"index","method":"POST","url":"/index.php/apps/flowupload/upload","message":"Call to a member function file_exists() on null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1","exception":{"Exception":"Exception","Message":"Call to a member function file_exists() on null","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Call to a member function file_exists() on null","Code":0,"Trace":[{"file":"/var/www/html/apps/flowupload/lib/Controller/UploadController.php","line":84,"function":"file_exists","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"upload","class":"OCA\\flowupload\\Controller\\UploadController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/Files/Filesystem.php","Line":678},"CustomMessage":"--"}}
{"reqId":"w6Z2ldFkYyhCE5mJ10LJ","level":3,-time-34+00:00",XXX,"user":"XXX","app":"index","method":"POST","url":"/index.php/apps/flowupload/upload","message":"Call to a member function file_exists() on null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1","exception":{"Exception":"Exception","Message":"Call to a member function file_exists() on null","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Call to a member function file_exists() on null","Code":0,"Trace":[{"file":"/var/www/html/apps/flowupload/lib/Controller/UploadController.php","line":84,"function":"file_exists","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"upload","class":"OCA\\flowupload\\Controller\\UploadController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/Files/Filesystem.php","Line":678},"CustomMessage":"--"}}
{"reqId":"dTFpZTvECfRogbIi9KZF","level":3,-time-34+00:00",XXX,"user":"XXX","app":"PHP","method":"POST","url":"/index.php/apps/flowupload/upload","message":"POST Content-Length of 1049779 bytes exceeds the limit of 999 bytes at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"wRz7c8Ng2Q1HqR5LYeyL","level":3,-time-34+00:00",XXX,"user":"XXX","app":"PHP","method":"POST","url":"/index.php/apps/flowupload/upload","message":"POST Content-Length of 1049779 bytes exceeds the limit of 999 bytes at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"ZjKfmjCMZpocoPHf8o9z","level":3,-time-34+00:00",XXX,"user":"XXX","app":"PHP","method":"POST","url":"/index.php/apps/flowupload/upload","message":"POST Content-Length of 1049779 bytes exceeds the limit of 999 bytes at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"w6Z2ldFkYyhCE5mJ10LJ","level":3,-time-34+00:00",XXX,"user":"XXX","app":"PHP","method":"POST","url":"/index.php/apps/flowupload/upload","message":"POST Content-Length of 1049779 bytes exceeds the limit of 999 bytes at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
```

**Comment by elasticSteel** [comment]
> I can verify this works in NC 22.2.6, I had to go into the "info.xml" and change the dependency version and wala!

The "beta" version also works in NC23.0.3, whereas v1.1.3 does not, at least for me.

**Comment by Donixon** [comment]
> > I can verify this works in NC 22.2.6, I had to go into the "info.xml" and change the dependency version and wala!
> 
> The "beta" version also works in NC23.0.3, whereas v1.1.3 does not, at least for me.

Can confirm, 1.1.2 does work, and 1.1.3 not. Newest version just gives en error at any file.

**Comment by elasticSteel** [comment]
> > I can verify this works in NC 22.2.6, I had to go into the "info.xml" and change the dependency version and wala!
> 
> The "beta" version also works in NC23.0.3, whereas v1.1.3 does not, at least for me.

Same Old Situation for NC24.0.0. "Beta" works fine, v1.1.3 doesn't.
I just need to be careful not to update it accidentally  ;-) ;-)

**Comment by updatedb** [comment]
> 

\OC_Util::setupFS();

lack "\" to find the function

**Comment by updatedb** [comment]
> I added a potential fix ([bb6c554](https://github.com/e-alfred/flowupload/commit/bb6c554679aa890deff285ddd27ec32f85b02a02)), can you test it by manually adding the changed lines and see if it works? The filesystem calls need to be set up separately now it seems.
> 
> @JonathanTreffler I tried to build it again, but it seems like there is a problem with the Vue frontend code:
> 
> ```
> Uncaught TypeError: Object(...) is not a function
>     <anonymous> App.vue:3
>     Webpack 3
> App.vue:3:111
>     <anonymous> App.vue:3
>     Webpack 3
> ```

it doesn't work.

you need add "\" in the function call

\OC_Util::setupFS();
