### ISSUE TITLE
BUG - doesn't download files in directories names containing some chars like "é", "è", "à" ...

### ISSUE THREAD

**Issue by Larsene** [e-alfred/flowupload#7]
If you try to upload files in directories who contains soms characters likes "é è à, ...", flowupload refuse to upload these files.

simply rename the directory before uploading fix the problem, so i'm quite sure flowupload has some pbs with these letters

**Comment by e-alfred** [comment]
Do you mean a directory name with special characters or files inside the directories with special characters? And what do you mean by "downloading files"? Flowupload only uploads files.

**Comment by Larsene** [comment]
Sorry, i mean uploading, of course, not downloading.

If the directory name with special characters, it's not working. files with special characters, it works.

![flowupload](https://user-images.githubusercontent.com/8544729/31070057-4acfbb3a-a75f-11e7-979d-800b0cc68154.png)

**Comment by Larsene** [comment]
and this appears in logs :
![screenshot_4](https://user-images.githubusercontent.com/8544729/31070405-7a013c2a-a760-11e7-9d0d-5ba7dd6378a1.jpg)

**Comment by sikrew** [comment]
I had the same issue and managed to fix it. 
I edited the file `flowupload/ajax/upload.php` by adding the characters that were causing me this issue.

Went from this:
 `$path = preg_replace('/[^a-z0-9 \(\)\.\-_\/]/i', '', $path);`
To this:
`$path = preg_replace('/[^a-z0-9äöüßáàâãéèêíìîóòõôúùûºªç&$%*#@ \(\)\.\-_\/]/i', '', $path);`

Hope this helps someone.

:)

**Comment by e-alfred** [comment]
@sikrew If you would like you can submit a PR and I will include this in the next release. The most difficult part is to find out each unsupported character which cloud make the list quite long after all.

**Comment by Larsene** [comment]
@sikrew : Thanks ! I've modified it and it works.

I've added some french special chars too (like ï, ë, etc.)

**Comment by e-alfred** [comment]
A negated character class might be a better option because it simply replaces everything that isn't allowed actually:

$path = preg_replace('/([^a-zA-Z0-9]+)/', '', $path);

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/flowupload/commit/1b2d0921588fb25f88d6ebde02b9f1a639747298.

**Comment by PenguinFreeDom** [comment]
This issue is still in version 0.0.7 with danish charters "ÆØÅ".....charters dossent get replaced....files are not uploaded

**Comment by rootbdfy** [comment]
I tried
$path = preg_replace('/([^а-яА-ЯёЁa-zA-Z0-9]+)/', '', $path);
but i see
Моде?низа?иямод?ляимпо??аМегаГИСЭ?ап?2и3План1mpp
instead 
Модернизация модуля им.mpp

**Comment by sosed213** [comment]
The same problem exists when loading files with Russian names. The file seems to be loaded, but not displayed. A file with hieroglyphs appears in the Linux directory (01 �� �� - ��-��.mp3)

**Comment by alxdc9** [comment]
Same with character 'ë'.

**Comment by ngmdat** [comment]
Hi Guys,
I have the problem when upload windows folder name with Multibytes Character (ex: Japanese, Chinese, so on ...)

**Comment by e-alfred** [comment]
@nfcg Can you create a PR with your fix?

**Comment by e-alfred** [comment]
@Larsene @sikrew @PenguinFreeDom @sosed213 @ngmdat @alxdc9 Please test the patch provided by @nfcg from this PR to see if this fixes all the problems with filenames containing special characters: https://github.com/e-alfred/flowupload/pull/47

If this solves the problem, I will publish a new release soon with this fix.
